package ar.edu.utn.frba.ddsi.common.models.enums;

public enum TipoEvento {
    AUSENCIA_PLATAFORMA,
    DONACION_ASIGNADA_ENTIDAD,
    DONACION_ASIGNADA_DONANTE,
    INICIO_RUTA_DONANTE,
    INICIO_RUTA_ENTIDAD,
    ENTREGA_EXITOSA_ENTIDAD,
    ENTREGA_EXITOSA_DONANTE,
    ENTREGA_FALLIDA
}
