server.port=8082
spring.application.name=notificaciones-service
spring.threads.virtual.enabled=true

notificaciones.db.driver=org.postgresql.Driver
notificaciones.db.url=${NOTIFICACIONES_DB_URL:jdbc:postgresql://localhost:5432/donaciones}
notificaciones.db.username=${NOTIFICACIONES_DB_USERNAME:postgres}
notificaciones.db.password=${NOTIFICACIONES_DB_PASSWORD:postgres}
notificaciones.db.dialect=org.hibernate.dialect.PostgreSQL10Dialect
notificaciones.db.hbm2ddl=update
notificaciones.db.show-sql=false
